services:
  api:
    container_name: CommandCentralAPI
    build: .
    ports:
      - 127.0.0.1:5100:5067
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Prod
      ASPNETCORE_HTTP_PORTS: 5067
      ENABLE_REGISTER: true

  db:
    container_name: CommandCentralDB
    image: postgres:16
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 1s
      retries: 120
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgres/data
volumes:
  db:
