// <auto-generated />
using System;
using API.SharedAPI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.SharedAPI.Persistence.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20240715221528_InitialAPIMigration")]
    partial class InitialAPIMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Household.Models.HouseholdModel", b =>
                {
                    b.Property<string>("HouseholdId")
                        .HasColumnType("text")
                        .HasColumnName("householdid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp")
                        .HasColumnName("lastmodified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("HouseholdId")
                        .HasName("pk_households");

                    b.ToTable("households", (string)null);
                });

            modelBuilder.Entity("API.Household.Models.HouseholdUsersModel", b =>
                {
                    b.Property<string>("HouseholdId")
                        .HasColumnType("text")
                        .HasColumnName("householdid");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("HouseholdId", "UserId")
                        .HasName("pk_householdusers");

                    b.ToTable("HouseholdUsers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
